#!/bin/bash

# prefer to compile against our own copy of SDL 1.x
echo Compiling our internal SDL 1.x
(cd vs2015/sdl && ./build-dosbox.sh) || exit 1

# now compile ourself
echo Compiling DOSBox-X
chmod +x configure
# FIXME: I would like MinGW builds to enable the debugger, eventually
./configure --enable-core-inline --disable-mt32 --prefix=/usr || exit 1
make -j3 || exit 1

