#!/bin/bash

# I'm sick and tired of all the churn the three versions of autoconf
# are causing in this repo. Stop committing the configure scripts
# and just autoregen.
./autogen.sh || exit 1

# fix
chmod +x vs2015/sdl/build-scripts/strip_fPIC.sh

chmod +x configure
./configure --enable-core-inline --enable-debug=heavy --enable-avcodec --prefix=/usr --enable-sdl2 || exit 1
make -j3 || exit 1

