#!/bin/bash

# I'm sick and tired of all the churn the three versions of autoconf
# are causing in this repo. Stop committing the configure scripts
# and just autoregen.
./autogen.sh || exit 1

# where are we?
top=`pwd`
if test -z "$top" ; then exit 1; fi

# fix
chmod +x vs2015/sdl/build-scripts/strip_fPIC.sh

# prefer to compile against our own copy of SDL 1.x
echo Compiling our internal SDL 1.x
(cd vs2015/sdl && ./build-dosbox.sh) || exit 1

# now compile ourself
echo Compiling DOSBox-X
chmod +x configure
./configure --enable-core-inline --enable-debug=heavy --prefix=/usr "$@" || exit 1 # --enable-avcodec
make -j3 || exit 1

