#!/usr/bin/env bash

# allow 32-bit on 64-bit (x86) builds
if [ "${1}" == "32" ]; then
    CC="$(which gcc) -m32"
    CXX="$(which g++) -m32"
    export CC CXX
    shift
fi

# I'm sick and tired of all the churn the three versions of autoconf
# are causing in this repo. Stop committing the configure scripts
# and just autoregen.
./autogen.sh || exit 1

# fix
chmod +x vs/sdl/build-scripts/strip_fPIC.sh

chmod +x configure

CFLAGS="${CFLAGS} -g3 -O0 -fno-inline -fno-omit-frame-pointer"
CXXFLAGS="${CXXFLAGS} -g3 -O0 -fno-inline -fno-omit-frame-pointer"
export CFLAGS CXXFLAGS

# prefer to compile against our own copy of SDL 1.x
echo "Compiling our internal SDL 1.x"
(cd vs/sdl && ./build-dosbox.sh) || exit 1

# prefer to compile against our own copy of SDLnet 1.x
echo "Compiling our internal SDLnet 1.x"
(cd vs/sdlnet && ./build-dosbox.sh) || exit 1

# now compile ourself
echo "Compiling DOSBox-X"
# NTS: --disable-dynamic-core is needed. the dynamic core doesn't work properly with the CFLAGS given above
./configure --enable-debug=heavy --prefix=/usr --disable-dynamic-core "${@}" || exit 1
make -j3 || exit 1

