#!/usr/bin/env bash

# allow 32-bit on 64-bit (x86) builds
if [ "$1" == "32" ]; then
    export CC=`which gcc`" -m32"
    export CXX=`which g++`" -m32"
    shift
    opt="--host=i686-pc-linux-gnu --target=i686-pc-linux-gnu"
fi

# I'm sick and tired of all the churn the three versions of autoconf
# are causing in this repo. Stop committing the configure scripts
# and just autoregen.
./autogen.sh || exit 1

export CFLAGS="$CFLAGS -pg -fprofile-arcs"
export CXXFLAGS="$CXXFLAGS -pg -fprofile-arcs"

# fix
chmod +x vs/sdl/build-scripts/strip_fPIC.sh

# prefer to compile against our own copy of SDL 1.x
echo Compiling our internal SDL 1.x
(cd vs/sdl && ./build-dosbox.sh) || exit 1

# prefer to compile against our own copy of SDLnet 1.x
echo Compiling our internal SDLnet 1.x
(cd vs/sdlnet && ./build-dosbox.sh) || exit 1

# now compile ourself
echo Compiling DOSBox-X
chmod +x configure
./configure --enable-debug=heavy --prefix=/usr "$@" $opt || exit 1
make -j3 || exit 1

