#!/bin/bash

# I'm sick and tired of all the churn the three versions of autoconf
# are causing in this repo. Stop committing the configure scripts
# and just autoregen.
./autogen.sh || exit 1

# fix
chmod +x vs2015/sdl/build-scripts/strip_fPIC.sh

# prefer to compile against our own copy of SDL 2.x IF the system does not provide one
x=`which sdl2-config`
if test -z "$x" ; then
    echo Compiling our internal SDL 2.x
    (cd vs2015/sdl2 && ./build-dosbox.sh) || exit 1
fi

chmod +x configure
./configure --enable-core-inline --enable-debug=heavy --enable-avcodec --prefix=/usr --enable-sdl2 || exit 1
make -j3 || exit 1

