#!/bin/bash
src/dosbox-x -defaultconf -defaultdir . -exit -fastlaunch -c 'config -wcp dosbox-x.commonref.conf' -c 'config -all -wcp dosbox-x.reference.conf' || exit 1

# Convert to Unix format if needed
dos2unix dosbox-x.commonref.conf
dos2unix dosbox-x.reference.conf

