#!/usr/bin/env bash
set -e
shopt -s extglob

# Poorly written shell script to update the wiki
# on the dosbox-x site
# ./update-wiki path/to/site/wiki path/to/dosbox-x.wiki

if [ ! -d "$1" ] || [ ! -d "$2" ]; then
  echo "Usage: update-wiki path/to/site/wiki path/to/dosbox-x.wiki"
  exit 1
fi

localbak="`pwd`"
tempdir="`mktemp -d`"
destdir="`realpath $1`"
srcdir="`realpath $2`"
spfiles="$destdir/index.html
$destdir/guides.asciidoc
$destdir/docinfo"

function cleanup {
  echo "Removing temp files"
  rm -r $tempdir || true
  cd $localbak
}
trap cleanup EXIT

function no_deps {
  echo "Please install project deps with Bundler"
  echo "  $ bundle install"
  exit 1
}
which bundle 1>/dev/null || no_deps
bundle exec asciidoctor -v 1>/dev/null || no_deps

echo "Copying files"
rmdir $tempdir || true
cp -r $srcdir $tempdir
rm -rf $tempdir/.git || true
cp -r -t $tempdir $spfiles

echo "Generating wiki in $tempdir"
bundle exec asciidoctor \
  -S server \
  -b html5 -d article \
  -a linkcss -a copycss \
  -a reproducible \
  -a source-highlighter=rouge \
  -a nofooter \
  -a docinfo=shared -a docinfodir=docinfo \
  $tempdir/*.asciidoc
rm $tempdir/!(guides).asciidoc

echo "Copying files over"
rm -r $destdir
cp -r $tempdir $destdir
