#!/usr/bin/env bash
set -e

# Poorly written shell script to update the wiki
# on the dosbox-x site
# ./update-wiki
#   path/to/site/wiki path/to/copy/of/dosbox-x.wiki

localbak="`pwd`"
tempdir="`mktemp -d`"
destdir="`realpath $1`"
srcdir="`realpath $2`"
spfiles="$destdir/index.html
$destdir/guides.html
$destdir/copy-to-clipboard.js
$destdir/octicons-16.svg
$destdir/docinfo-footer.html"

function no_deps {
  echo "Please install project deps with Bundler"
  echo "  $ bundle install"
  exit 1
}

function cleanup {
  echo "Removing temp files"
  rm -r $tempdir || true
  cd $localbak
}
trap cleanup EXIT

which bundle 1>/dev/null || no_deps
bundle exec asciidoctor -v 1>/dev/null || no_deps

echo "Copying files"
rmdir $tempdir || true
cp -r $srcdir $tempdir
rm -rf $tempdir/.git || true

echo "Adding header to files"
sed -i -e '
1i:source-highlighter: rouge\
:docinfo: shared-footer' $tempdir/*.asciidoc
cp -t $tempdir $spfiles

echo "Generating wiki in $tempdir"
bundle exec asciidoctor -b html5 -d book $tempdir/*.asciidoc
rm $tempdir/*.asciidoc

echo "Copying files over"
rm -r $destdir
cp -r $tempdir $destdir
