#!/bin/bash
src/dosbox-x -defaultconf -defaultdir . -silent -c 'config -wcp dosbox-x.reference.conf' -c 'config -all -wcp dosbox-x.reference.full.conf' -c 'config -setup -wcp contrib/windows/installer/dosbox-x.reference.setup.conf' || exit 1

# Convert to Unix format if needed
dos2unix dosbox-x.reference.conf
dos2unix dosbox-x.reference.full.conf
unix2dos contrib/windows/installer/dosbox-x.reference.setup.conf
