[sdl]
autolock = false
waitonerror = false

[log]
logfile = dosbox-x.log
misc = debug

[dosbox]
machine = svga_s3
memsize = 16
startbanner = false

[cpu]
cycles = max

[mixer]
rate = 22050
blocksize = 1024
prebuffer = 25

[vbeai]
vbeai = true

[sblaster]
sbtype = none

[gus]
gus = false

[speaker]
pcspeaker = false
tandy = off
disney = false
ps1audio = off

[autoexec]
mount c .
c:
vbeaiwav.exe guppy.wav > out.txt
exit
