/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.28.2-0-g031912c4b (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.28.2-0-g031912c4b"
#endif
#define SDL_REVISION_NUMBER 0
