# Common variables for FindSDL2*.cmake modules

set(_inc_suffixes include)
set(_lib_suffixes)
if(MSVC)
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        list(APPEND _lib_suffixes "lib/x86")
    endif()
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        list(APPEND _lib_suffixes "lib/x64")
    endif()
endif()
if(MINGW)
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        list(APPEND _lib_suffixes "i686-w64-mingw32/lib")
        list(APPEND _inc_suffixes "i686-w64-mingw32/include")
    endif()
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        list(APPEND _lib_suffixes "x86_46-w64-mingw32/lib")
        list(APPEND _inc_suffixes "x86_46-w64-mingw32/include")
    endif()
endif()