ifdef::env-github[:suffixappend:]
ifndef::env-github[:suffixappend: .html]

Sound Blaster DSP commands by value
-----------------------------------

* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE0[0xE0 (DSP identification)]
SB2.0+
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE1[0xE1 (Get DSP version)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE2[0xE2 (DMA identification)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE3[0xE3 (DSP copyright
string)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE4[0xE4 (Write test register)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE5[0xE5]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE6[0xE6]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE7[0xE7]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE8[0xE8 (Read test register)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE9[0xE9]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xEA[0xEA]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xEB[0xEB]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xEC[0xEC]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xED[0xED]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xEE[0xEE]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xEF[0xEF]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF0[0xF0]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF1[0xF1]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF2[0xF2 (Trigger 8-bit IRQ)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF3[0xF3 (Trigger 16-bit IRQ)]
SB16+
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF4[0xF4]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF5[0xF5]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF6[0xF6]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF7[0xF7]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF8[0xF8] (DOSBox:
Undocumented pre-SB16 that returns 0x00?)
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF9[0xF9] (DOSBox: SB16+ ASP
functions?)
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFA[0xFA]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFB[0xFB]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFC[0xFC]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFD[0xFD]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFE[0xFE]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xFF[0xFF]

Sound Blaster DSP commands by group
-----------------------------------

DSP identification
~~~~~~~~~~~~~~~~~~

* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE0[0xE0 (DSP identification)]
SB2.0+
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE1[0xE1 (Get DSP version)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE3[0xE3 (DSP copyright
string)]

Resource test
~~~~~~~~~~~~~

* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE2[0xE2 (DMA identification)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF2[0xF2 (Trigger 8-bit IRQ)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xF3[0xF3 (Trigger 16-bit IRQ)]
SB16+

Other/misc
~~~~~~~~~~

* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE4[0xE4 (Write test register)]
* link:Hardware%3ASound-Blaster%3ADSP-commands%3A0xE8[0xE8 (Read test register)]

External references
-------------------

* http://the.earth.li/~tfm/oldpage/sb_dsp.html[TFM’s DSP commands]
* http://hackipedia.org/Platform/x86/Sound/Creative%20Labs/ISA,%20Sound%20Blaster/pdf/Sound%20Blaster%20Series%20Developer%20Kit%2c%20Second%20Edition.pdf[Developer
Kit for Sound Blaster Series, Second Edition]
