name: Bug report
description: File a bug report to help us improve DOSBox-X
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the form as cleanly as possible.
        It's highly recommended for you to fill in all the fields (even optional ones) if possible, so it's easier for us to solve the problem. Also, make sure that you have properly filled in the title of the bug report.
  - type: textarea
    id: issue
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help in explaining.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behaviour
      description: How can we reproduce this bug? For example, doing what actions in what software causes the bug to occur?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: excepted
    attributes:
      label: Expected behavior
      description: A clear and concise description of what did you expect to happen. If applicable, add screenshots to help in explaining.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: What operating system(s) this bug have occurred on?
      description: Put in the release name of the OS (additionally with a extra version number and/or an architecture name) this problem have occurred on.
      placeholder: "Ex. Windows 10 21H2, Ubuntu 21.04 etc."
    validations:
      required: true
  # This is confusing
  #- type: input
  #  id: hardware
  #  attributes:
  #    label: Relevant hardware info
  #    description: If relevant, describe the hardware this bug have occurred on.
  #    placeholder: "CPU, GPU, device brand/model, installed drivers, etc. Ex. Raspberry Pi 3B+, etc."
  #  validations:
  #    required: false
  - type: input
    id: version
    attributes:
      label: What version(s) of DOSBox-X have this bug?
      description: Put in the release version or git commit/branch and additionally the flavor of the DOSBox-X build this problem occurred on. Though, please always check if the bug occurs in the latest version/commit.
      placeholder: "Ex. 0.83.17 SDL1 Visual Studio, commit 88370683291f5c681d2a7d6fff088b947b783bd4 SDL1 etc."
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Used configuration
      description: Share the configuration (usually from the `dosbox-x.conf` or `dosbox.conf` file) that caused the bug to occur. Leave this area empty if you're using the default configuration. If you want to link to a upload of the file, please put the link into the "Additional information" box instead.
      render: ini # Syntax highlighting
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Output log
      description: The relevant log DOSBox-X outputted when the problem occurred. If you want to link to a upload of the file, please put the link into the "Additional information" box instead.
      render: text # Syntax highlighting
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional information
      description: Add more information about the problem here.
    validations:
      required: false
  - type: checkboxes
    id: alreadyexists
    attributes:
      label: Have you checked that no similar bug report(s) exist?
      description: Please try to search for this bug in the issues before creating this bug report.
      options:
        - label: I have searched and didn't find any similar bug report.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/joncampbell123/dosbox-x/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/joncampbell123/dosbox-x/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the code of conduct and the contributing guidelines.
          required: true
