name: Question
description: Ask for support or start a discussion about DOSBox-X
labels: question

body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the form as cleanly as possible.
        Also, make sure that you have properly filled in the title of the question.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/joncampbell123/dosbox-x/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/joncampbell123/dosbox-x/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the code of conduct and the contributing guidelines.
          required: true
  - type: checkboxes
    id: alreadyexists
    attributes:
      label: Have you checked that no other similar question(s) already exists?
      description: Search the issues before creating this question.
      options:
        - label: I have searched and didn't find any similar issues.
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of what your question is. If applicable, add screenshots to help in explaining.
      placeholder: "Ex. How do I [...]"
    validations:
      required: true
