CONFIG Class Reference
CONFIG.COM utility to control configuration and files.
Public Member Functions
void Run (void)
Program entry point, when the command is run.
Detailed Description
CONFIG.COM utility to control configuration and files.
Utility to write configuration, set configuration, and other configuration related functions.
Definition at line 513 of file programs.cpp.
Member Function Documentation
void CONFIG::Run (void) [virtual]
Program entry point, when the command is run.
lin=linestr,
lin=linestr,
Implements Program.
Definition at line 554 of file programs.cpp.
References Program::cmd, Program::exit_status, Program::SetEnv(), Program::WriteExitStatus(), and Program::WriteOut().
The documentation for this class was generated from the following file:
src/misc/programs.cpp