GUI::WindowInWindow Class Reference
Public Member Functions
WindowInWindow (Window *parent, int x, int y, int w, int h)
virtual bool mouseDragged (int x, int y, MouseButton button)
Mouse was moved while a button was pressed. Returns true if event was handled.
virtual bool mouseDown (int x, int y, MouseButton button)
Mouse was pressed. Returns true if event was handled.
virtual bool mouseUp (int x, int y, MouseButton button)
Mouse was released. Returns true if event was handled.
virtual bool mouseMoved (int x, int y)
Mouse was moved. Returns true if event was handled.
virtual bool mouseClicked (int x, int y, MouseButton button)
Mouse was clicked. Returns true if event was handled.
virtual bool mouseDoubleClicked (int x, int y, MouseButton button)
Mouse was double-clicked. Returns true if event was handled.
virtual bool keyDown (const Key &key)
Key was pressed. Returns true if event was handled.
virtual void paintAll (Drawable &d) const
Draw this window's content including all children.
virtual void resize (int w, int h)
Resize this window to the given dimensions.
virtual void enableScrollBars (bool hs, bool vs)
virtual void enableBorder (bool en)
Public Attributes
bool hscroll_dragging = false
bool vscroll_dragging = false
bool dragging = false
int drag_x = 0
int drag_y = 0
int scroll_pos_x = 0
int scroll_pos_y = 0
int scroll_pos_w = 0
int scroll_pos_h = 0
bool hscroll = false
bool vscroll = false
int hscroll_display_width = 16
int vscroll_display_width = 16
bool border = false
Protected Member Functions
void scrollToWindow (Window *child)
Detailed Description
Definition at line 782 of file gui_tk.h.
Member Function Documentation
bool GUI::WindowInWindow::mouseClicked (int x, int y, MouseButton button) [virtual]
Mouse was clicked. Returns true if event was handled.
Clicking means pressing and releasing the mouse button while not moving it.
Reimplemented from GUI::Window.
Definition at line 2296 of file gui_tk.cpp.
void GUI::WindowInWindow::resize (int w, int h) [virtual]
Resize this window to the given dimensions.
If that would move part of the window outside of this window's area, the outside area will silently be clipped while drawing.
Reimplemented from GUI::Window.
Definition at line 2324 of file gui_tk.cpp.
References GUI::Window::children, GUI::Window::getHeight(), GUI::Window::getWidth(), GUI::Window::getX(), and GUI::Window::getY().
Referenced by GUI::MessageBox2::setText().
The documentation for this class was generated from the following files:
src/libs/gui_tk/gui_tk.h
src/libs/gui_tk/gui_tk.cpp