#define PACKAGE "dosbox-x"
#define PACKAGE_BUGREPORT "https://github.com/joncampbell123/dosbox-x/issues"
#define PACKAGE_NAME "dosbox-x"
#define PACKAGE_STRING "dosbox-x 2025.05.03"
#define PACKAGE_TARNAME "dosbox-x"
#define PACKAGE_URL "https://dosbox-x.com"
#define PACKAGE_VERSION "2025.05.03"
#define VERSION "2025.05.03"
#define COPYRIGHT_YEAR "2025"
