var searchData=
[
  ['badconversion',['BadConversion',['../classBadConversion.html',1,'']]],
  ['batchfile',['BatchFile',['../classBatchFile.html',1,'']]],
  ['bios',['BIOS',['../classBIOS.html',1,'']]],
  ['bitmapfont',['BitmapFont',['../classGUI_1_1BitmapFont.html',1,'GUI']]],
  ['bitseqlengthandpos_5fret_5ft',['bitseqlengthandpos_ret_t',['../classbitop_1_1bitseqlengthandpos__ret__t.html',1,'bitop']]],
  ['block',['Block',['../classRegionAllocTracking_1_1Block.html',1,'RegionAllocTracking']]],
  ['boot',['BOOT',['../classBOOT.html',1,'']]],
  ['bootsector',['bootSector',['../unionbootSector.html',1,'']]],
  ['borderedwindow',['BorderedWindow',['../classGUI_1_1BorderedWindow.html',1,'GUI']]],
  ['bpb_5funion_5ft',['bpb_union_t',['../unionbpb__union__t.html',1,'']]],
  ['bpb_5funion_5ft',['bpb_union_t',['../unionFAT__BootSector_1_1bpb__union__t.html',1,'FAT_BootSector']]],
  ['breverbmodel',['BReverbModel',['../classMT32Emu_1_1BReverbModel.html',1,'MT32Emu']]],
  ['breverbsettings',['BReverbSettings',['../structMT32Emu_1_1BReverbSettings.html',1,'MT32Emu']]],
  ['builtinfileblob',['BuiltinFileBlob',['../structBuiltinFileBlob.html',1,'']]],
  ['button',['Button',['../classGUI_1_1Button.html',1,'GUI']]],
  ['button_5fevent',['button_event',['../structbutton__event.html',1,'']]],
  ['bx_5fne2k_5fc',['bx_ne2k_c',['../classbx__ne2k__c.html',1,'']]],
  ['bx_5fne2k_5ft',['bx_ne2k_t',['../structbx__ne2k__t.html',1,'']]]
];
