//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winres.rc
//
#define ID_SEPARATOR                    0
#define VS_VERSION_INFO                 1
#define AFX_IDC_LISTBOX                 100
#define AFX_IDC_CHANGE                  101
#define IDR_MENU                        101
#define AFX_IDC_BROWSER                 102
#define dosbox_ico                      102
#define ID_OPENFILE                     103
#define ID_KEYMAP                       104
#define ID_DOSBOX_SECTION               105
#define ID_CAPMOUSE                     106
#define ID_PAUSE                        107
#define ID_SURFACE                      108
#define ID_DDRAW                        109
#define ID_OPENGL                       110
#define ID_OPENGLNB                     111
#define ID_OPENGLHQ                     112
#define ID_DIRECT3D                     113
#define ID_D3D_PS                       114
#define ID_TOGGLE                       115
#define ID_HIDECYCL                     116
#define ID_REFRESH                      117
#define ID_QUIT                         118
#define ID_AUTOCYCLE                    119
#define ID_AUTODETER                    120
#define ID_NORMAL                       121
#define ID_DYNAMIC                      122
#define ID_FULL                         123
#define ID_SIMPLE                       124
#define ID_AUTO                         125
#define ID_CPUTYPE_AUTO                 126
#define ID_CPUTYPE_386                  127
#define ID_CPUTYPE_386_PREFETCH         128
#define ID_CPUTYPE_486                  129
#define ID_CPUTYPE_PENTIUM              130
#define ID_FULLSCREEN                   131
#define ID_ASPECT                       132
#define ID_NONE                         133
#define ID_ADVMAME2X                    134
#define ID_ADVMAME3X                    135
#define ID_HQ2X                         136
#define ID_HQ3X                         137
#define ID_ADVINTERP2X                  138
#define ID_ADVINTERP3X                  139
#define ID_TV2X                         140
#define ID_TV3X                         141
#define ID_SCAN2X                       142
#define ID_SCAN3X                       143
#define ID_RGB2X                        144
#define ID_RGB3X                        145
#define ID_NORMAL2X                     146
#define ID_NORMAL3X                     147
#define ID_HARDWARE2X                   148
#define ID_HARDWARE3X                   149
#define ID_2XSAI                        150
#define ID_SUPER2XSAI                   151
#define ID_SUPEREAGLE                   152
#define ID_VSYNC_ON                     153
#define ID_VSYNC_OFF                    154
#define ID_VSYNC_FORCE                  155
#define ID_VSYNC                        156
#define ID_MIXER_SECTION                157
#define ID_SB_NONE                      158
#define ID_SB_SB1                       159
#define ID_SB_SB2                       160
#define ID_SB_SBPRO1                    161
#define ID_SB_SBPRO2                    162
#define ID_SB_SB16                      163
#define ID_SB_GB                        164
#define ID_SB_220                       165
#define ID_SB_240                       166
#define ID_SB_260                       167
#define ID_SB_280                       168
#define ID_SB_2a0                       169
#define ID_SB_2c0                       170
#define ID_SB_2e0                       171
#define ID_SB_300                       172
#define ID_SB_IRQ_3                     173
#define ID_SB_IRQ_5                     174
#define ID_SB_IRQ_7                     175
#define ID_SB_IRQ_9                     176
#define ID_SB_IRQ_10                    177
#define ID_SB_IRQ_11                    178
#define ID_SB_IRQ_12                    179
#define ID_SB_DMA_0                     180
#define ID_SB_DMA_1                     181
#define ID_SB_DMA_3                     182
#define ID_SB_DMA_5                     183
#define ID_SB_DMA_6                     184
#define ID_SB_DMA_7                     185
#define ID_SB_HDMA_0                    186
#define ID_SB_HDMA_1                    187
#define ID_SB_HDMA_3                    188
#define ID_SB_HDMA_5                    189
#define ID_SB_HDMA_6                    190
#define ID_SB_HDMA_7                    191
#define ID_SB_OPL_NONE                  192
#define ID_SB_OPL_AUTO                  193
#define ID_SB_OPL_CMS                   194
#define ID_SB_OPL_OPL2                  195
#define ID_SB_OPL_DUALOPL2              196
#define ID_SB_OPL_OPL3                  197
#define ID_SB_OPL_49716                 198
#define ID_SB_OPL_48000                 199
#define ID_SB_OPL_44100                 200
#define AFX_IDC_PRINT_DOCNAME           201
#define ID_SB_OPL_32000                 201
#define AFX_IDC_PRINT_PRINTERNAME       202
#define ID_SB_OPL_22050                 202
#define AFX_IDC_PRINT_PORTNAME          203
#define ID_SB_OPL_16000                 203
#define AFX_IDC_PRINT_PAGENUM           204
#define ID_SB_OPL_11025                 204
#define ID_SB_OPL_8000                  205
#define ID_SB_OPL_EMU_DEFAULT           206
#define ID_SB_OPL_EMU_COMPAT            207
#define ID_SB_OPL_EMU_FAST              208
#define ID_GUS_TRUE                     209
#define ID_GUS_FALSE                    210
#define ID_GUS_44100                    211
#define ID_GUS_48000                    212
#define ID_GUS_32000                    213
#define ID_GUS_22050                    214
#define ID_GUS_16000                    215
#define ID_GUS_11025                    216
#define ID_GUS_8000                     217
#define ID_GUS_49716                    218
#define ID_GUS_240                      219
#define ID_GUS_220                      220
#define ID_GUS_260                      221
#define ID_GUS_280                      222
#define ID_GUS_2a0                      223
#define ID_GUS_2c0                      224
#define ID_GUS_2e0                      225
#define ID_GUS_300                      226
#define ID_GUS_IRQ_5                    227
#define ID_GUS_IRQ_3                    228
#define ID_GUS_IRQ_7                    229
#define ID_GUS_IRQ_9                    230
#define ID_GUS_IRQ_10                   231
#define ID_GUS_IRQ_11                   232
#define ID_GUS_IRQ_12                   233
#define ID_GUS_DMA_0                    234
#define ID_GUS_DMA_3                    235
#define ID_GUS_DMA_1                    236
#define ID_GUS_DMA_5                    237
#define ID_GUS_DMA_6                    238
#define ID_GUS_DMA_7                    239
#define ID_PCSPEAKER_TRUE               240
#define ID_PCSPEAKER_FALSE              241
#define ID_PCSPEAKER_49716              242
#define ID_PCSPEAKER_48000              243
#define ID_PCSPEAKER_44100              244
#define ID_PCSPEAKER_32000              245
#define ID_PCSPEAKER_22050              246
#define ID_PCSPEAKER_16000              247
#define ID_PCSPEAKER_11025              248
#define ID_PCSPEAKER_8000               249
#define ID_TANDY_ON                     250
#define ID_TANDY_OFF                    251
#define ID_TANDY_AUTO                   252
#define ID_TANDY_49716                  253
#define ID_TANDY_48000                  254
#define ID_TANDY_44100                  255
#define ID_TANDY_32000                  256
#define ID_TANDY_22050                  257
#define ID_TANDY_16000                  258
#define ID_TANDY_11025                  259
#define ID_TANDY_8000                   260
#define ID_MIDI_NONE                    261
#define ID_MIDI_UART                    262
#define ID_MIDI_INTELLI                 263
#define ID_MIDI_DEFAULT                 264
#define ID_MIDI_ALSA                    265
#define ID_MIDI_OSS                     266
#define ID_MIDI_WIN32                   267
#define ID_MIDI_COREAUDIO               268
#define ID_MIDI_COREMIDI                269
#define ID_MIDI_MT32                    270
#define ID_MIDI_DEV_NONE                271
#define ID_DISNEY_TRUE                  272
#define ID_DISNEY_FALSE                 273
#define ID_INNOVA_TRUE                  274
#define ID_INNOVA_FALSE                 275
#define ID_INNOVA_220                   276
#define ID_INNOVA_240                   277
#define ID_INNOVA_260                   278
#define ID_INNOVA_300                   279
#define ID_INNOVA_49716                 280
#define ID_INNOVA_48000                 281
#define ID_INNOVA_44100                 282
#define ID_INNOVA_32000                 283
#define ID_INNOVA_22050                 284
#define ID_INNOVA_11025                 285
#define ID_INNOVA_16000                 286
#define ID_INNOVA_8000                  287
#define ID_INNOVA_280                   288
#define ID_INNOVA_2A0                   289
#define ID_INNOVA_2C0                   290
#define ID_INNOVA_2E0                   291
#define ID_INNOVA_3                     292
#define ID_INNOVA_2                     293
#define ID_INNOVA_1                     294
#define ID_INNOVA_0                     295
#define ID_CYCLE                        296
#define ID_XMS                          297
#define ID_EMS_TRUE                     298
#define ID_EMS_FALSE                    299
#define ID_EMS_EMM386                   300
#define ID_EMS_EMSBOARD                 301
#define ID_UMB                          302
#define ID_IPXNET                       303
#define ID_SSHOT                        304
#define ID_MOVIE                        305
#define ID_WAVE                         306
#define ID_OPL                          307
#define ID_MIDI                         308
#define ID_UMOUNT_A                     309
#define ID_UMOUNT_B                     310
#define ID_UMOUNT_C                     311
#define ID_UMOUNT_D                     312
#define ID_UMOUNT_E                     313
#define ID_UMOUNT_F                     314
#define ID_UMOUNT_G                     315
#define ID_UMOUNT_H                     316
#define ID_UMOUNT_I                     317
#define ID_UMOUNT_J                     318
#define ID_UMOUNT_K                     319
#define ID_UMOUNT_L                     320
#define ID_UMOUNT_M                     321
#define ID_UMOUNT_N                     322
#define ID_UMOUNT_O                     323
#define ID_UMOUNT_P                     324
#define ID_UMOUNT_Q                     325
#define ID_UMOUNT_R                     326
#define ID_UMOUNT_S                     327
#define ID_UMOUNT_T                     328
#define ID_UMOUNT_U                     329
#define ID_UMOUNT_V                     330
#define ID_UMOUNT_W                     331
#define ID_UMOUNT_X                     332
#define ID_UMOUNT_Y                     333
#define ID_UMOUNT_Z                     334
#define ID_AUTOMOUNT_A                  335
#define ID_AUTOMOUNT_B                  336
#define ID_AUTOMOUNT_C                  337
#define ID_AUTOMOUNT_D                  338
#define ID_AUTOMOUNT_E                  339
#define ID_AUTOMOUNT_F                  340
#define ID_AUTOMOUNT_G                  341
#define ID_AUTOMOUNT_H                  342
#define ID_AUTOMOUNT_I                  343
#define ID_AUTOMOUNT_J                  344
#define ID_AUTOMOUNT_K                  345
#define ID_AUTOMOUNT_L                  346
#define ID_AUTOMOUNT_M                  347
#define ID_AUTOMOUNT_N                  348
#define ID_AUTOMOUNT_O                  349
#define ID_AUTOMOUNT_P                  350
#define ID_AUTOMOUNT_Q                  351
#define ID_AUTOMOUNT_R                  352
#define ID_AUTOMOUNT_S                  353
#define ID_AUTOMOUNT_T                  354
#define ID_AUTOMOUNT_U                  355
#define ID_AUTOMOUNT_V                  356
#define ID_AUTOMOUNT_W                  357
#define ID_AUTOMOUNT_X                  358
#define ID_AUTOMOUNT_Y                  359
#define ID_MOUNT_CDROM_A                360
#define ID_MOUNT_CDROM_B                361
#define ID_MOUNT_CDROM_C                362
#define ID_MOUNT_CDROM_D                363
#define ID_MOUNT_CDROM_E                364
#define ID_MOUNT_CDROM_F                365
#define ID_MOUNT_CDROM_G                366
#define ID_MOUNT_CDROM_H                367
#define ID_MOUNT_CDROM_I                368
#define ID_MOUNT_CDROM_J                369
#define ID_MOUNT_CDROM_K                370
#define ID_MOUNT_CDROM_L                371
#define ID_MOUNT_CDROM_M                372
#define ID_MOUNT_CDROM_N                373
#define ID_MOUNT_CDROM_O                374
#define ID_MOUNT_CDROM_P                375
#define ID_MOUNT_CDROM_Q                376
#define ID_MOUNT_CDROM_R                377
#define ID_MOUNT_CDROM_S                378
#define ID_MOUNT_CDROM_T                379
#define ID_MOUNT_CDROM_U                380
#define ID_MOUNT_CDROM_V                381
#define ID_MOUNT_CDROM_W                382
#define ID_MOUNT_CDROM_X                383
#define ID_MOUNT_CDROM_Y                384
#define ID_MOUNT_FLOPPY_A               385
#define ID_MOUNT_FLOPPY_B               386
#define ID_MOUNT_FLOPPY_C               387
#define ID_MOUNT_FLOPPY_D               388
#define ID_MOUNT_FLOPPY_E               389
#define ID_MOUNT_FLOPPY_F               390
#define ID_MOUNT_FLOPPY_G               391
#define ID_MOUNT_FLOPPY_H               392
#define ID_MOUNT_FLOPPY_I               393
#define ID_MOUNT_FLOPPY_J               394
#define ID_MOUNT_FLOPPY_K               395
#define ID_MOUNT_FLOPPY_L               396
#define ID_MOUNT_FLOPPY_M               397
#define ID_MOUNT_FLOPPY_N               398
#define ID_MOUNT_FLOPPY_O               399
#define ID_MOUNT_FLOPPY_P               400
#define ID_MOUNT_FLOPPY_Q               401
#define ID_MOUNT_FLOPPY_R               402
#define ID_MOUNT_FLOPPY_S               403
#define ID_MOUNT_FLOPPY_T               404
#define ID_MOUNT_FLOPPY_U               405
#define ID_MOUNT_FLOPPY_V               406
#define ID_MOUNT_FLOPPY_W               407
#define ID_MOUNT_FLOPPY_X               408
#define ID_MOUNT_FLOPPY_Y               409
#define ID_MOUNT_LOCAL_A                410
#define ID_MOUNT_LOCAL_B                411
#define ID_MOUNT_LOCAL_C                412
#define ID_MOUNT_LOCAL_D                413
#define ID_MOUNT_LOCAL_E                414
#define ID_MOUNT_LOCAL_F                415
#define ID_MOUNT_LOCAL_G                416
#define ID_MOUNT_LOCAL_H                417
#define ID_MOUNT_LOCAL_I                418
#define ID_MOUNT_LOCAL_J                419
#define ID_MOUNT_LOCAL_K                420
#define ID_MOUNT_LOCAL_L                421
#define ID_MOUNT_LOCAL_M                422
#define ID_MOUNT_LOCAL_N                423
#define ID_MOUNT_LOCAL_O                424
#define ID_MOUNT_LOCAL_P                425
#define ID_MOUNT_LOCAL_Q                426
#define ID_MOUNT_LOCAL_R                427
#define ID_MOUNT_LOCAL_S                428
#define ID_MOUNT_LOCAL_T                429
#define ID_MOUNT_LOCAL_U                430
#define ID_MOUNT_LOCAL_V                431
#define ID_MOUNT_LOCAL_W                432
#define ID_MOUNT_LOCAL_X                433
#define ID_MOUNT_LOCAL_Y                434
#define ID_MOUNT_IMAGE_A                435
#define ID_MOUNT_IMAGE_B                436
#define ID_MOUNT_IMAGE_C                437
#define ID_MOUNT_IMAGE_D                438
#define ID_MOUNT_IMAGE_E                439
#define ID_MOUNT_IMAGE_F                440
#define ID_MOUNT_IMAGE_G                441
#define ID_MOUNT_IMAGE_H                442
#define ID_MOUNT_IMAGE_I                443
#define ID_MOUNT_IMAGE_J                444
#define ID_MOUNT_IMAGE_K                445
#define ID_MOUNT_IMAGE_L                446
#define ID_MOUNT_IMAGE_M                447
#define ID_MOUNT_IMAGE_N                448
#define ID_MOUNT_IMAGE_O                449
#define ID_MOUNT_IMAGE_P                450
#define ID_MOUNT_IMAGE_Q                451
#define ID_MOUNT_IMAGE_R                452
#define ID_MOUNT_IMAGE_S                453
#define ID_MOUNT_IMAGE_T                454
#define ID_MOUNT_IMAGE_U                455
#define ID_MOUNT_IMAGE_V                456
#define ID_MOUNT_IMAGE_W                457
#define ID_MOUNT_IMAGE_X                458
#define ID_MOUNT_IMAGE_Y                459
#define ID_FORCESCALER                  460
#define ID_VSYNC_HOST                   461
#define ID_OVERLAY                      462
#define ID_WINRES_USER                  463
#define ID_WINRES_DESKTOP               464
#define ID_WINFULL_USER                 465
#define ID_WINFULL_DESKTOP              466
#define ID_WINRES_ORIGINAL              467
#define ID_WINFULL_ORIGINAL             468
#define ID_KEY_NONE                     469
#define ID_KEY_BG                       470
#define ID_KEY_CZ                       471
#define ID_KEY_FR                       472
#define ID_KEY_GK                       473
#define ID_KEY_GR                       474
#define ID_KEY_HR                       475
#define ID_KEY_HU                       476
#define ID_KEY_SV                       477
#define ID_KEY_IT                       478
#define ID_KEY_NL                       479
#define ID_KEY_NO                       480
#define ID_KEY_PL                       481
#define ID_KEY_RU                       482
#define ID_KEY_SK                       483
#define ID_KEY_SP                       484
#define ID_KEY_SU                       485
#define ID_FULLDOUBLE                   486
#define ID_AUTOLOCK                     487
#define ID_MOUSE                        488
#define ID_JOYSTICKTYPE_AUTO            489
#define ID_JOYSTICKTYPE_2AXIS           490
#define ID_JOYSTICKTYPE_4AXIS           491
#define ID_JOYSTICKTYPE_4AXIS_2         492
#define ID_JOYSTICKTYPE_FCS             493
#define ID_JOYSTICKTYPE_CH              494
#define ID_JOYSTICKTYPE_NONE            495
#define ID_JOYSTICK_TIMED               496
#define ID_JOYSTICK_AUTOFIRE            497
#define ID_JOYSTICK_SWAP34              498
#define ID_JOYSTICK_BUTTONWRAP          499
#define ID_SERIAL_SECTION               500
#define ID_PARALLEL_SECTION             501
#define ID_NE2000_SECTION               502
#define ID_BOOT_A                       503
#define ID_BOOT_C                       504
#define ID_BOOT_D                       505
#define ID_HDD_SIZE                     506
#define ID_WAITONERR                    507
#define ID_USESCANCODES                 508
#define ID_KEY_BE                       509
#define ID_KEY_BR                       510
#define ID_KEY_CF                       511
#define ID_KEY_DK                       512
#define ID_KEY_LA                       513
#define ID_KEY_PO                       514
#define ID_KEY_SF                       515
#define ID_KEY_SG                       516
#define ID_KEY_UK                       517
#define ID_KEY_US                       518
#define ID_KEY_YU                       519
#define ID_KEY_FO                       520
#define ID_KEY_MK                       521
#define ID_KEY_MT                       522
#define ID_KEY_PH                       523
#define ID_KEY_RO                       524
#define ID_KEY_SQ                       525
#define ID_KEY_TM                       526
#define ID_KEY_TR                       527
#define ID_KEY_UX                       528
#define ID_KEY_YC                       529
#define ID_KEY_DV                       530
#define ID_KEY_RH                       531
#define ID_KEY_LH                       532
#define ID_SAVESTATE_1                  533
#define ID_SAVESTATE_2                  534
#define ID_SAVESTATE_3                  535
#define ID_SAVESTATE_4                  536
#define ID_SAVESTATE_5                  537
#define ID_SAVESTATE_6                  538
#define ID_SAVESTATE_7                  539
#define ID_SAVESTATE_8                  540
#define ID_SAVESTATE_9                  541
#define ID_SAVESTATE_10                 542
#define ID_LOADSTATE_1                  543
#define ID_LOADSTATE_2                  544
#define ID_LOADSTATE_3                  545
#define ID_LOADSTATE_4                  546
#define ID_LOADSTATE_5                  547
#define ID_LOADSTATE_6                  548
#define ID_LOADSTATE_7                  549
#define ID_LOADSTATE_8                  550
#define ID_LOADSTATE_9                  551
#define ID_LOADSTATE_10                 552
#define ID_AUTOEXEC                     553
#define ID_SAVELANG                     554
#define ID_PRINTER_SECTION              555
#define ID_MIDI_MT32_REVERBMODE_AUTO    556
#define ID_MIDI_MT32_REVERBMODE_0       557
#define ID_MIDI_MT32_REVERBMODE_1       558
#define ID_MIDI_MT32_REVERBMODE_2       559
#define ID_MIDI_MT32_REVERBMODE_3       560
#define ID_MIDI_MT32_REVERBTIME_0       561
#define ID_MIDI_MT32_REVERBTIME_1       562
#define ID_MIDI_MT32_REVERBTIME_2       563
#define ID_MIDI_MT32_REVERBTIME_3       564
#define ID_MIDI_MT32_REVERBTIME_4       565
#define ID_MIDI_MT32_REVERBTIME_5       566
#define ID_MIDI_MT32_REVERBTIME_6       567
#define ID_MIDI_MT32_REVERBTIME_7       568
#define ID_MIDI_MT32_REVERBLEV_0        569
#define ID_MIDI_MT32_REVERBLEV_1        570
#define ID_MIDI_MT32_REVERBLEV_2        571
#define ID_MIDI_MT32_REVERBLEV_3        572
#define ID_MIDI_MT32_REVERBLEV_4        573
#define ID_MIDI_MT32_REVERBLEV_5        574
#define ID_MIDI_MT32_REVERBLEV_6        575
#define ID_MIDI_MT32_REVERBLEV_7        576
#define ID_RESTART                      577
#define ID_GLIDE_TRUE                   578
#define ID_GLIDE_EMU                    579
#define ID_SB_HW210                     580
#define ID_SB_HW220                     581
#define ID_SB_HW230                     582
#define ID_SB_HW240                     583
#define ID_SB_HW250                     584
#define ID_SB_HW260                     585
#define ID_SB_HW280                     586
#define ID_SB_OPL_HARDWARE              587
#define ID_SB_OPL_HARDWAREGB            588
#define ID_MIDI_MT32_49716              589
#define ID_MIDI_MT32_48000              590
#define ID_MIDI_MT32_32000              591
#define ID_MIDI_MT32_16000              592
#define ID_MIDI_MT32_8000               593
#define ID_REMOVE_STATE_1               594
#define ID_REMOVE_STATE_2               595
#define ID_REMOVE_STATE_3               596
#define ID_REMOVE_STATE_4               597
#define ID_REMOVE_STATE_5               598
#define ID_REMOVE_STATE_6               599
#define ID_REMOVE_STATE_7               600
#define ID_REMOVE_STATE_8               601
#define ID_REMOVE_STATE_9               602
#define ID_REMOVE_STATE_10              603
#define ID_REMOVE_STATE_ALL             604
#define ID_CHAR9                        606
#define ID_MULTISCAN                    607
#define ID_CPU_ADVANCED                 608
#define ID_DOS_ADVANCED                 609
#define ID_MIDI_SYNTH                   610
#define ID_MIDI_TIMIDITY                611
#define ID_PS1_ON                       612
#define ID_PS1_OFF                      613
#define ID_PS1_49716                    614
#define ID_PS1_48000                    615
#define ID_PS1_44100                    616
#define ID_PS1_32000                    617
#define ID_PS1_22050                    618
#define ID_PS1_16000                    619
#define ID_PS1_11025                    620
#define ID_PS1_8000                     621
#define ID_MIDI_ADVANCED                622
#define ID_MOUSE_VERTICAL               623
#define ID_MIDI_MT32_DAC_AUTO           624
#define ID_MIDI_MT32_DAC_0              625
#define ID_MIDI_MT32_DAC_1              626
#define ID_MIDI_MT32_DAC_2              627
#define ID_MIDI_MT32_DAC_3              628
#define ID_MIDI_MT32_REVERSESTEREO_TRUE 629
#define ID_MIDI_MT32_REVERSESTEREO_FALSE 630
#define ID_OVERSCAN_0                   631
#define ID_OVERSCAN_1                   632
#define ID_OVERSCAN_2                   633
#define ID_OVERSCAN_3                   634
#define ID_OVERSCAN_4                   635
#define ID_OVERSCAN_5                   636
#define ID_OVERSCAN_6                   637
#define ID_OVERSCAN_7                   638
#define ID_OVERSCAN_8                   639
#define ID_OVERSCAN_9                   640
#define ID_OVERSCAN_10                  641
#define ID_DRVFORCE_DIRECTX             642
#define ID_DRVFORCE_WINDIB              643
#define ID_DRVFORCE_AUTO                644
#define ID_CPUTYPE_PENTIUM_MMX          645
#define ID_SB_SB16VIBRA                 646
#define ID_MUTE                         647
#define ID_SWAPSTEREO                   648
#define ID_SEND_CTRL_ESC                649
#define ID_SEND_ALT_TAB                 650
#define ID_SEND_CTRL_ALT_DEL            651
#define ID_AUTOMOUNT_Z                  652
#define ID_MOUNT_LOCAL_Z                653
#define ID_MOUNT_CDROM_Z                654
#define ID_MOUNT_FLOPPY_Z               655
#define ID_MOUNT_IMAGE_Z                656
#define ID_BOOT_A_MOUNTED               657
#define ID_BOOT_C_MOUNTED               658
#define ID_BOOT_D_MOUNTED               659
#define ID_XBRZ                         660
#define ID_NORMAL4X                     661
#define ID_NORMAL5X                     662
#define ID_HARDWARE_NONE                663
#define ID_HARDWARE4X                   664
#define ID_HARDWARE5X                   665
#define ID_CPU_TURBO                    666
#define ID_SKIP_0                       667
#define ID_SKIP_1                       668
#define ID_SKIP_2                       669
#define ID_SKIP_3                       670
#define ID_SKIP_4                       671
#define ID_SKIP_5                       672
#define ID_SKIP_6                       673
#define ID_SKIP_7                       674
#define ID_SKIP_8                       675
#define ID_SKIP_9                       676
#define ID_SKIP_10                      677
#define ID_RATE_1_DELAY_1               678
#define ID_RATE_2_DELAY_1               679
#define ID_RATE_3_DELAY_1               680
#define ID_RATE_4_DELAY_1               681
#define ID_RATE_5_DELAY_1               682
#define ID_RATE_6_DELAY_1               683
#define ID_RATE_7_DELAY_1               684
#define ID_RATE_8_DELAY_1               685
#define ID_RATE_9_DELAY_1               686
#define ID_RATE_10_DELAY_1              687
#define ID_RATE_11_DELAY_1              688
#define ID_RATE_12_DELAY_1              689
#define ID_RATE_13_DELAY_1              690
#define ID_RATE_14_DELAY_1              691
#define ID_RATE_15_DELAY_1              692
#define ID_RATE_16_DELAY_1              693
#define ID_RATE_17_DELAY_1              694
#define ID_RATE_18_DELAY_1              695
#define ID_RATE_19_DELAY_1              696
#define ID_RATE_20_DELAY_1              697
#define ID_RATE_21_DELAY_1              698
#define ID_RATE_22_DELAY_1              699
#define ID_RATE_23_DELAY_1              700
#define ID_RATE_24_DELAY_1              701
#define ID_RATE_25_DELAY_1              702
#define ID_RATE_26_DELAY_1              703
#define ID_RATE_27_DELAY_1              704
#define ID_RATE_28_DELAY_1              705
#define ID_RATE_29_DELAY_1              706
#define ID_RATE_30_DELAY_1              707
#define ID_RATE_31_DELAY_1              708
#define ID_RATE_32_DELAY_1              709
#define ID_RATE_1_DELAY_2               710
#define ID_RATE_2_DELAY_2               711
#define ID_RATE_3_DELAY_2               712
#define ID_RATE_4_DELAY_2               713
#define ID_RATE_5_DELAY_2               714
#define ID_RATE_6_DELAY_2               715
#define ID_RATE_7_DELAY_2               716
#define ID_RATE_8_DELAY_2               717
#define ID_RATE_9_DELAY_2               718
#define ID_RATE_10_DELAY_2              719
#define ID_RATE_11_DELAY_2              720
#define ID_RATE_12_DELAY_2              721
#define ID_RATE_13_DELAY_2              722
#define ID_RATE_14_DELAY_2              723
#define ID_RATE_15_DELAY_2              724
#define ID_RATE_16_DELAY_2              725
#define ID_RATE_17_DELAY_2              726
#define ID_RATE_18_DELAY_2              727
#define ID_RATE_19_DELAY_2              728
#define ID_RATE_20_DELAY_2              729
#define ID_RATE_21_DELAY_2              730
#define ID_RATE_22_DELAY_2              731
#define ID_RATE_23_DELAY_2              732
#define ID_RATE_24_DELAY_2              733
#define ID_RATE_25_DELAY_2              734
#define ID_RATE_26_DELAY_2              735
#define ID_RATE_27_DELAY_2              736
#define ID_RATE_28_DELAY_2              737
#define ID_RATE_29_DELAY_2              738
#define ID_RATE_30_DELAY_2              739
#define ID_RATE_31_DELAY_2              740
#define ID_RATE_32_DELAY_2              741
#define ID_RATE_1_DELAY_3               742
#define ID_RATE_2_DELAY_3               743
#define ID_RATE_3_DELAY_3               744
#define ID_RATE_4_DELAY_3               745
#define ID_RATE_5_DELAY_3               746
#define ID_RATE_6_DELAY_3               747
#define ID_RATE_7_DELAY_3               748
#define ID_RATE_8_DELAY_3               749
#define ID_RATE_9_DELAY_3               750
#define ID_RATE_10_DELAY_3              751
#define ID_RATE_11_DELAY_3              752
#define ID_RATE_12_DELAY_3              753
#define ID_RATE_13_DELAY_3              754
#define ID_RATE_14_DELAY_3              755
#define ID_RATE_15_DELAY_3              756
#define ID_RATE_16_DELAY_3              757
#define ID_RATE_17_DELAY_3              758
#define ID_RATE_18_DELAY_3              759
#define ID_RATE_19_DELAY_3              760
#define ID_RATE_20_DELAY_3              761
#define ID_RATE_21_DELAY_3              762
#define ID_RATE_22_DELAY_3              763
#define ID_RATE_23_DELAY_3              764
#define ID_RATE_24_DELAY_3              765
#define ID_RATE_25_DELAY_3              766
#define ID_RATE_26_DELAY_3              767
#define ID_RATE_27_DELAY_3              768
#define ID_RATE_28_DELAY_3              769
#define ID_RATE_29_DELAY_3              770
#define ID_RATE_30_DELAY_3              771
#define ID_RATE_31_DELAY_3              772
#define ID_RATE_32_DELAY_3              773
#define ID_RATE_1_DELAY_4               774
#define ID_RATE_2_DELAY_4               775
#define ID_RATE_3_DELAY_4               776
#define ID_RATE_4_DELAY_4               777
#define ID_RATE_5_DELAY_4               778
#define ID_RATE_6_DELAY_4               779
#define ID_RATE_7_DELAY_4               780
#define ID_RATE_8_DELAY_4               781
#define ID_RATE_9_DELAY_4               782
#define ID_RATE_10_DELAY_4              783
#define ID_RATE_11_DELAY_4              784
#define ID_RATE_12_DELAY_4              785
#define ID_RATE_13_DELAY_4              786
#define ID_RATE_14_DELAY_4              787
#define ID_RATE_15_DELAY_4              788
#define ID_RATE_16_DELAY_4              789
#define ID_RATE_17_DELAY_4              790
#define ID_RATE_18_DELAY_4              791
#define ID_RATE_19_DELAY_4              792
#define ID_RATE_20_DELAY_4              793
#define ID_RATE_21_DELAY_4              794
#define ID_RATE_22_DELAY_4              795
#define ID_RATE_23_DELAY_4              796
#define ID_RATE_24_DELAY_4              797
#define ID_RATE_25_DELAY_4              798
#define ID_RATE_26_DELAY_4              799
#define ID_RATE_27_DELAY_4              800
#define ID_RATE_28_DELAY_4              801
#define ID_RATE_29_DELAY_4              802
#define ID_RATE_30_DELAY_4              803
#define ID_RATE_31_DELAY_4              804
#define ID_RATE_32_DELAY_4              805
#define ID_MOUSE_SENSITIVITY            806
#define ID_AUTOMOUNT                    807
#define ID_GLIDE_LFB_FULL               808
#define ID_GLIDE_LFB_FULL_NOAUX         809
#define ID_GLIDE_LFB_READ               810
#define ID_GLIDE_LFB_READ_NOAUX         811
#define ID_GLIDE_LFB_WRITE              812
#define ID_GLIDE_LFB_WRITE_NOAUX        813
#define ID_GLIDE_LFB_NONE               814
#define ID_GLIDE_SPLASH                 815
#define ID_GLIDE_EMU_FALSE              816
#define ID_GLIDE_EMU_SOFTWARE           817
#define ID_GLIDE_EMU_OPENGL             818
#define ID_GLIDE_EMU_AUTO               819
#define ID_ALWAYS_ON_TOP                820
#define ID_MFCLOC_MANIFEST              1000
#define AFX_IDC_FONTPROP                1000
#define AFX_IDC_FONTNAMES               1001
#define AFX_IDC_FONTSTYLES              1002
#define AFX_IDC_FONTSIZES               1003
#define AFX_IDC_STRIKEOUT               1004
#define AFX_IDC_UNDERLINE               1005
#define AFX_IDC_SAMPLEBOX               1006
#define AFX_IDC_COLOR_BLACK             1100
#define AFX_IDC_COLOR_WHITE             1101
#define AFX_IDC_COLOR_RED               1102
#define AFX_IDC_COLOR_GREEN             1103
#define AFX_IDC_COLOR_BLUE              1104
#define AFX_IDC_COLOR_YELLOW            1105
#define AFX_IDC_COLOR_MAGENTA           1106
#define AFX_IDC_COLOR_CYAN              1107
#define AFX_IDC_COLOR_GRAY              1108
#define AFX_IDC_COLOR_LIGHTGRAY         1109
#define AFX_IDC_COLOR_DARKRED           1110
#define AFX_IDC_COLOR_DARKGREEN         1111
#define AFX_IDC_COLOR_DARKBLUE          1112
#define AFX_IDC_COLOR_LIGHTBROWN        1113
#define AFX_IDC_COLOR_DARKMAGENTA       1114
#define AFX_IDC_COLOR_DARKCYAN          1115
#define AFX_IDC_COLORPROP               1116
#define AFX_IDC_SYSTEMCOLORS            1117
#define AFX_IDC_PROPNAME                1201
#define AFX_IDC_PICTURE                 1202
#define AFX_IDC_BROWSE                  1203
#define AFX_IDC_CLEAR                   1204
#define AFX_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define AFX_IDD_NEWTYPEDLG              30721
#define AFX_IDD_PRINTDLG                30722
#define AFX_IDD_PREVIEW_TOOLBAR         30723
#define AFX_IDD_INSERTOBJECT            30724
#define AFX_IDD_CHANGEICON              30725
#define AFX_IDD_CONVERT                 30726
#define AFX_IDD_PASTESPECIAL            30727
#define AFX_IDD_EDITLINKS               30728
#define AFX_IDD_FILEBROWSE              30729
#define AFX_IDD_BUSY                    30730
#define AFX_IDD_OBJECTPROPERTIES        30732
#define AFX_IDD_CHANGESOURCE            30733
#define AFX_IDD_EMPTYDIALOG             30734
#define AFX_IDC_CONTEXTHELP             30977
#define AFX_IDC_MAGNIFY                 30978
#define AFX_IDC_SMALLARROWS             30979
#define AFX_IDC_HSPLITBAR               30980
#define AFX_IDC_VSPLITBAR               30981
#define AFX_IDC_NODROPCRSR              30982
#define AFX_IDC_TRACKNWSE               30983
#define AFX_IDC_TRACKNESW               30984
#define AFX_IDC_TRACKNS                 30985
#define AFX_IDC_TRACKWE                 30986
#define AFX_IDC_TRACK4WAY               30987
#define AFX_IDC_MOVE4WAY                30988
#define AFX_IDB_MINIFRAME_MENU          30994
#define AFX_IDB_CHECKLISTBOX_95         30996
#define AFX_IDR_PREVIEW_ACCEL           30997
#define AFX_IDC_MOUSE_PAN_NW            30998
#define AFX_IDC_MOUSE_PAN_N             30999
#define AFX_IDC_MOUSE_PAN_NE            31000
#define AFX_IDC_MOUSE_PAN_W             31001
#define AFX_IDC_MOUSE_PAN_HV            31002
#define AFX_IDC_MOUSE_PAN_E             31003
#define AFX_IDC_MOUSE_PAN_SW            31004
#define AFX_IDC_MOUSE_PAN_S             31005
#define AFX_IDC_MOUSE_PAN_SE            31006
#define AFX_IDC_MOUSE_PAN_HORZ          31007
#define AFX_IDC_MOUSE_PAN_VERT          31008
#define AFX_IDC_MOUSE_ORG_HORZ          31009
#define AFX_IDC_MOUSE_ORG_VERT          31010
#define AFX_IDC_MOUSE_ORG_HV            31011
#define AFX_IDC_MOUSE_MASK              31012
#define AFX_IDI_STD_MDIFRAME            31233
#define AFX_IDI_STD_FRAME               31234
#define AFX_IDD_PROPPAGE_COLOR          32257
#define AFX_IDD_PROPPAGE_FONT           32258
#define AFX_IDD_PROPPAGE_PICTURE        32259
#define AFX_IDB_TRUETYPE                32384
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define AFX_IDS_APP_TITLE_EMBEDDING     0xE003
#define AFX_IDS_COMPANY_NAME            0xE004
#define AFX_IDS_OBJ_TITLE_INPLACE       0xE005
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_NEW_FRAME               0xE10D
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_FORMAT_FONT                  0xE160
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define AFX_ID_PREVIEW_CLOSE            0xE300
#define AFX_ID_PREVIEW_NUMPAGE          0xE301
#define AFX_ID_PREVIEW_NEXT             0xE302
#define AFX_ID_PREVIEW_PREV             0xE303
#define AFX_ID_PREVIEW_PRINT            0xE304
#define AFX_ID_PREVIEW_ZOOMIN           0xE305
#define AFX_ID_PREVIEW_ZOOMOUT          0xE306
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_INDICATOR_KANA               0xE706
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REBAR                   0xE804
#define ID_VIEW_AUTOARRANGE             0xE805
#define ID_VIEW_SMALLICON               0xE810
#define ID_VIEW_LARGEICON               0xE811
#define ID_VIEW_LIST                    0xE812
#define ID_VIEW_DETAILS                 0xE813
#define ID_VIEW_LINEUP                  0xE814
#define ID_VIEW_BYNAME                  0xE815
#define ID_RECORD_FIRST                 0xE900
#define ID_RECORD_LAST                  0xE901
#define ID_RECORD_NEXT                  0xE902
#define ID_RECORD_PREV                  0xE903
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_DESKACCESSORY           0xEFDA
#define AFX_IDS_OPENFILE                0xF000
#define AFX_IDS_SAVEFILE                0xF001
#define AFX_IDS_ALLFILTER               0xF002
#define AFX_IDS_UNTITLED                0xF003
#define AFX_IDS_SAVEFILECOPY            0xF004
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define AFX_IDS_UNNAMED_FILE            0xF006
#define AFX_IDS_HIDE                    0xF011
#define AFX_IDP_NO_ERROR_AVAILABLE      0xF020
#define AFX_IDS_NOT_SUPPORTED_EXCEPTION 0xF021
#define AFX_IDS_RESOURCE_EXCEPTION      0xF022
#define AFX_IDS_MEMORY_EXCEPTION        0xF023
#define AFX_IDS_USER_EXCEPTION          0xF024
#define AFX_IDS_INVALID_ARG_EXCEPTION   0xF025
#define AFX_IDS_PRINTONPORT             0xF040
#define AFX_IDS_ONEPAGE                 0xF041
#define AFX_IDS_TWOPAGE                 0xF042
#define AFX_IDS_PRINTPAGENUM            0xF043
#define AFX_IDS_PREVIEWPAGEDESC         0xF044
#define AFX_IDS_PRINTDEFAULTEXT         0xF045
#define AFX_IDS_PRINTDEFAULT            0xF046
#define AFX_IDS_PRINTFILTER             0xF047
#define AFX_IDS_PRINTCAPTION            0xF048
#define AFX_IDS_PRINTTOFILE             0xF049
#define AFX_IDS_OBJECT_MENUITEM         0xF080
#define AFX_IDS_EDIT_VERB               0xF081
#define AFX_IDS_ACTIVATE_VERB           0xF082
#define AFX_IDS_CHANGE_LINK             0xF083
#define AFX_IDS_AUTO                    0xF084
#define AFX_IDS_MANUAL                  0xF085
#define AFX_IDS_FROZEN                  0xF086
#define AFX_IDS_ALL_FILES               0xF087
#define AFX_IDS_SAVE_MENU               0xF088
#define AFX_IDS_UPDATE_MENU             0xF089
#define AFX_IDS_SAVE_AS_MENU            0xF08A
#define AFX_IDS_SAVE_COPY_AS_MENU       0xF08B
#define AFX_IDS_EXIT_MENU               0xF08C
#define AFX_IDS_UPDATING_ITEMS          0xF08D
#define AFX_IDS_METAFILE_FORMAT         0xF08E
#define AFX_IDS_DIB_FORMAT              0xF08F
#define AFX_IDS_BITMAP_FORMAT           0xF090
#define AFX_IDS_LINKSOURCE_FORMAT       0xF091
#define AFX_IDS_EMBED_FORMAT            0xF092
#define AFX_IDS_PASTELINKEDTYPE         0xF094
#define AFX_IDS_UNKNOWNTYPE             0xF095
#define AFX_IDS_RTF_FORMAT              0xF096
#define AFX_IDS_TEXT_FORMAT             0xF097
#define AFX_IDS_INVALID_CURRENCY        0xF098
#define AFX_IDS_INVALID_DATETIME        0xF099
#define AFX_IDS_INVALID_DATETIMESPAN    0xF09A
#define AFX_IDP_INVALID_FILENAME        0xF100
#define AFX_IDP_FAILED_TO_OPEN_DOC      0xF101
#define AFX_IDP_FAILED_TO_SAVE_DOC      0xF102
#define AFX_IDP_ASK_TO_SAVE             0xF103
#define AFX_IDP_FAILED_TO_CREATE_DOC    0xF104
#define AFX_IDP_FILE_TOO_LARGE          0xF105
#define AFX_IDP_FAILED_TO_START_PRINT   0xF106
#define AFX_IDP_FAILED_TO_LAUNCH_HELP   0xF107
#define AFX_IDP_INTERNAL_FAILURE        0xF108
#define AFX_IDP_COMMAND_FAILURE         0xF109
#define AFX_IDP_FAILED_MEMORY_ALLOC     0xF10A
#define AFX_IDP_UNREG_DONE              0xF10B
#define AFX_IDP_UNREG_FAILURE           0xF10C
#define AFX_IDP_DLL_LOAD_FAILED         0xF10D
#define AFX_IDP_DLL_BAD_VERSION         0xF10E
#define AFX_IDP_PARSE_INT               0xF110
#define AFX_IDP_PARSE_REAL              0xF111
#define AFX_IDP_PARSE_INT_RANGE         0xF112
#define AFX_IDP_PARSE_REAL_RANGE        0xF113
#define AFX_IDP_PARSE_STRING_SIZE       0xF114
#define AFX_IDP_PARSE_RADIO_BUTTON      0xF115
#define AFX_IDP_PARSE_BYTE              0xF116
#define AFX_IDP_PARSE_UINT              0xF117
#define AFX_IDP_PARSE_DATETIME          0xF118
#define AFX_IDP_PARSE_CURRENCY          0xF119
#define AFX_IDP_PARSE_GUID              0xF11A
#define AFX_IDP_PARSE_TIME              0xF11B
#define AFX_IDP_PARSE_DATE              0xF11C
#define AFX_IDP_FAILED_INVALID_FORMAT   0xF120
#define AFX_IDP_FAILED_INVALID_PATH     0xF121
#define AFX_IDP_FAILED_DISK_FULL        0xF122
#define AFX_IDP_FAILED_ACCESS_READ      0xF123
#define AFX_IDP_FAILED_ACCESS_WRITE     0xF124
#define AFX_IDP_FAILED_IO_ERROR_READ    0xF125
#define AFX_IDP_FAILED_IO_ERROR_WRITE   0xF126
#define AFX_IDP_SCRIPT_ERROR            0xF130
#define AFX_IDP_SCRIPT_DISPATCH_EXCEPTION 0xF131
#define AFX_IDP_STATIC_OBJECT           0xF180
#define AFX_IDP_FAILED_TO_CONNECT       0xF181
#define AFX_IDP_SERVER_BUSY             0xF182
#define AFX_IDP_BAD_VERB                0xF183
#define AFX_IDS_NOT_DOCOBJECT           0xF184
#define AFX_IDP_FAILED_TO_NOTIFY        0xF185
#define AFX_IDP_FAILED_TO_LAUNCH        0xF186
#define AFX_IDP_ASK_TO_UPDATE           0xF187
#define AFX_IDP_FAILED_TO_UPDATE        0xF188
#define AFX_IDP_FAILED_TO_REGISTER      0xF189
#define AFX_IDP_FAILED_TO_AUTO_REGISTER 0xF18A
#define AFX_IDP_FAILED_TO_CONVERT       0xF18B
#define AFX_IDP_GET_NOT_SUPPORTED       0xF18C
#define AFX_IDP_SET_NOT_SUPPORTED       0xF18D
#define AFX_IDP_ASK_TO_DISCARD          0xF18E
#define AFX_IDP_FAILED_TO_CREATE        0xF18F
#define AFX_IDP_FAILED_MAPI_LOAD        0xF190
#define AFX_IDP_INVALID_MAPI_DLL        0xF191
#define AFX_IDP_FAILED_MAPI_SEND        0xF192
#define AFX_IDP_FILE_NONE               0xF1A0
#define AFX_IDP_FILE_GENERIC            0xF1A1
#define AFX_IDP_FILE_NOT_FOUND          0xF1A2
#define AFX_IDP_FILE_BAD_PATH           0xF1A3
#define AFX_IDP_FILE_TOO_MANY_OPEN      0xF1A4
#define AFX_IDP_FILE_ACCESS_DENIED      0xF1A5
#define AFX_IDP_FILE_INVALID_FILE       0xF1A6
#define AFX_IDP_FILE_REMOVE_CURRENT     0xF1A7
#define AFX_IDP_FILE_DIR_FULL           0xF1A8
#define AFX_IDP_FILE_BAD_SEEK           0xF1A9
#define AFX_IDP_FILE_HARD_IO            0xF1AA
#define AFX_IDP_FILE_SHARING            0xF1AB
#define AFX_IDP_FILE_LOCKING            0xF1AC
#define AFX_IDP_FILE_DISKFULL           0xF1AD
#define AFX_IDP_FILE_EOF                0xF1AE
#define AFX_IDP_ARCH_NONE               0xF1B0
#define AFX_IDP_ARCH_GENERIC            0xF1B1
#define AFX_IDP_ARCH_READONLY           0xF1B2
#define AFX_IDP_ARCH_ENDOFFILE          0xF1B3
#define AFX_IDP_ARCH_WRITEONLY          0xF1B4
#define AFX_IDP_ARCH_BADINDEX           0xF1B5
#define AFX_IDP_ARCH_BADCLASS           0xF1B6
#define AFX_IDP_ARCH_BADSCHEMA          0xF1B7
#define AFX_IDS_OCC_SCALEUNITS_PIXELS   0xF1C0
#define AFX_IDS_STATUS_FONT             0xF230
#define AFX_IDS_TOOLTIP_FONT            0xF231
#define AFX_IDS_UNICODE_FONT            0xF232
#define AFX_IDS_MINI_FONT               0xF233
#define AFX_IDP_SQL_CONNECT_FAIL        0xF281
#define AFX_IDP_SQL_RECORDSET_FORWARD_ONLY 0xF282
#define AFX_IDP_SQL_EMPTY_COLUMN_LIST   0xF283
#define AFX_IDP_SQL_FIELD_SCHEMA_MISMATCH 0xF284
#define AFX_IDP_SQL_ILLEGAL_MODE        0xF285
#define AFX_IDP_SQL_MULTIPLE_ROWS_AFFECTED 0xF286
#define AFX_IDP_SQL_NO_CURRENT_RECORD   0xF287
#define AFX_IDP_SQL_NO_ROWS_AFFECTED    0xF288
#define AFX_IDP_SQL_RECORDSET_READONLY  0xF289
#define AFX_IDP_SQL_SQL_NO_TOTAL        0xF28A
#define AFX_IDP_SQL_ODBC_LOAD_FAILED    0xF28B
#define AFX_IDP_SQL_DYNASET_NOT_SUPPORTED 0xF28C
#define AFX_IDP_SQL_SNAPSHOT_NOT_SUPPORTED 0xF28D
#define AFX_IDP_SQL_API_CONFORMANCE     0xF28E
#define AFX_IDP_SQL_SQL_CONFORMANCE     0xF28F
#define AFX_IDP_SQL_NO_DATA_FOUND       0xF290
#define AFX_IDP_SQL_ROW_UPDATE_NOT_SUPPORTED 0xF291
#define AFX_IDP_SQL_ODBC_V2_REQUIRED    0xF292
#define AFX_IDP_SQL_NO_POSITIONED_UPDATES 0xF293
#define AFX_IDP_SQL_LOCK_MODE_NOT_SUPPORTED 0xF294
#define AFX_IDP_SQL_DATA_TRUNCATED      0xF295
#define AFX_IDP_SQL_ROW_FETCH           0xF296
#define AFX_IDP_SQL_INCORRECT_ODBC      0xF297
#define AFX_IDP_SQL_UPDATE_DELETE_FAILED 0xF298
#define AFX_IDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED 0xF299
#define AFX_IDP_SQL_FIELD_NOT_FOUND     0xF29A
#define AFX_IDP_SQL_BOOKMARKS_NOT_SUPPORTED 0xF29B
#define AFX_IDP_SQL_BOOKMARKS_NOT_ENABLED 0xF29C
#define AFX_IDS_DELETED                 0xF29D
#define AFX_IDP_DAO_ENGINE_INITIALIZATION 0xF2B0
#define AFX_IDP_DAO_DFX_BIND            0xF2B1
#define AFX_IDP_DAO_OBJECT_NOT_OPEN     0xF2B2
#define AFX_IDP_DAO_ROWTOOSHORT         0xF2B3
#define AFX_IDP_DAO_BADBINDINFO         0xF2B4
#define AFX_IDP_DAO_COLUMNUNAVAILABLE   0xF2B5
#define AFX_IDS_HTTP_TITLE              0xF2D1
#define AFX_IDS_HTTP_NO_TEXT            0xF2D2
#define AFX_IDS_HTTP_BAD_REQUEST        0xF2D3
#define AFX_IDS_HTTP_AUTH_REQUIRED      0xF2D4
#define AFX_IDS_HTTP_FORBIDDEN          0xF2D5
#define AFX_IDS_HTTP_NOT_FOUND          0xF2D6
#define AFX_IDS_HTTP_SERVER_ERROR       0xF2D7
#define AFX_IDS_HTTP_NOT_IMPLEMENTED    0xF2D8
#define AFX_IDS_CHECKLISTBOX_UNCHECK    0xF2E1
#define AFX_IDS_CHECKLISTBOX_CHECK      0xF2E2
#define AFX_IDS_CHECKLISTBOX_MIXED      0xF2E3
#define AFX_IDS_PROPPAGE_UNKNOWN        0xFE01
#define AFX_IDS_COLOR_DESKTOP           0xFE04
#define AFX_IDS_COLOR_APPWORKSPACE      0xFE05
#define AFX_IDS_COLOR_WNDBACKGND        0xFE06
#define AFX_IDS_COLOR_WNDTEXT           0xFE07
#define AFX_IDS_COLOR_MENUBAR           0xFE08
#define AFX_IDS_COLOR_MENUTEXT          0xFE09
#define AFX_IDS_COLOR_ACTIVEBAR         0xFE0A
#define AFX_IDS_COLOR_INACTIVEBAR       0xFE0B
#define AFX_IDS_COLOR_ACTIVETEXT        0xFE0C
#define AFX_IDS_COLOR_INACTIVETEXT      0xFE0D
#define AFX_IDS_COLOR_ACTIVEBORDER      0xFE0E
#define AFX_IDS_COLOR_INACTIVEBORDER    0xFE0F
#define AFX_IDS_COLOR_WNDFRAME          0xFE10
#define AFX_IDS_COLOR_SCROLLBARS        0xFE11
#define AFX_IDS_COLOR_BTNFACE           0xFE12
#define AFX_IDS_COLOR_BTNSHADOW         0xFE13
#define AFX_IDS_COLOR_BTNTEXT           0xFE14
#define AFX_IDS_COLOR_BTNHIGHLIGHT      0xFE15
#define AFX_IDS_COLOR_DISABLEDTEXT      0xFE16
#define AFX_IDS_COLOR_HIGHLIGHT         0xFE17
#define AFX_IDS_COLOR_HIGHLIGHTTEXT     0xFE18
#define AFX_IDS_REGULAR                 0xFE19
#define AFX_IDS_BOLD                    0xFE1A
#define AFX_IDS_ITALIC                  0xFE1B
#define AFX_IDS_BOLDITALIC              0xFE1C
#define AFX_IDS_SAMPLETEXT              0xFE1D
#define AFX_IDS_DISPLAYSTRING_FONT      0xFE1E
#define AFX_IDS_DISPLAYSTRING_COLOR     0xFE1F
#define AFX_IDS_DISPLAYSTRING_PICTURE   0xFE20
#define AFX_IDS_PICTUREFILTER           0xFE21
#define AFX_IDS_PICTYPE_UNKNOWN         0xFE22
#define AFX_IDS_PICTYPE_NONE            0xFE23
#define AFX_IDS_PICTYPE_BITMAP          0xFE24
#define AFX_IDS_PICTYPE_METAFILE        0xFE25
#define AFX_IDS_PICTYPE_ICON            0xFE26
#define AFX_IDS_COLOR_PPG               0xFE28
#define AFX_IDS_COLOR_PPG_CAPTION       0xFE29
#define AFX_IDS_FONT_PPG                0xFE2A
#define AFX_IDS_FONT_PPG_CAPTION        0xFE2B
#define AFX_IDS_PICTURE_PPG             0xFE2C
#define AFX_IDS_PICTURE_PPG_CAPTION     0xFE2D
#define AFX_IDS_PICTUREBROWSETITLE      0xFE30
#define AFX_IDS_BORDERSTYLE_0           0xFE31
#define AFX_IDS_BORDERSTYLE_1           0xFE32
#define AFX_IDS_VERB_EDIT               0xFE40
#define AFX_IDS_VERB_PROPERTIES         0xFE41
#define AFX_IDP_PICTURECANTOPEN         0xFE83
#define AFX_IDP_PICTURECANTLOAD         0xFE84
#define AFX_IDP_PICTURETOOLARGE         0xFE85
#define AFX_IDP_PICTUREREADFAILED       0xFE86
#define AFX_IDP_E_ILLEGALFUNCTIONCALL   0xFEA0
#define AFX_IDP_E_OVERFLOW              0xFEA1
#define AFX_IDP_E_OUTOFMEMORY           0xFEA2
#define AFX_IDP_E_DIVISIONBYZERO        0xFEA3
#define AFX_IDP_E_OUTOFSTRINGSPACE      0xFEA4
#define AFX_IDP_E_OUTOFSTACKSPACE       0xFEA5
#define AFX_IDP_E_BADFILENAMEORNUMBER   0xFEA6
#define AFX_IDP_E_FILENOTFOUND          0xFEA7
#define AFX_IDP_E_BADFILEMODE           0xFEA8
#define AFX_IDP_E_FILEALREADYOPEN       0xFEA9
#define AFX_IDP_E_DEVICEIOERROR         0xFEAA
#define AFX_IDP_E_FILEALREADYEXISTS     0xFEAB
#define AFX_IDP_E_BADRECORDLENGTH       0xFEAC
#define AFX_IDP_E_DISKFULL              0xFEAD
#define AFX_IDP_E_BADRECORDNUMBER       0xFEAE
#define AFX_IDP_E_BADFILENAME           0xFEAF
#define AFX_IDP_E_TOOMANYFILES          0xFEB0
#define AFX_IDP_E_DEVICEUNAVAILABLE     0xFEB1
#define AFX_IDP_E_PERMISSIONDENIED      0xFEB2
#define AFX_IDP_E_DISKNOTREADY          0xFEB3
#define AFX_IDP_E_PATHFILEACCESSERROR   0xFEB4
#define AFX_IDP_E_PATHNOTFOUND          0xFEB5
#define AFX_IDP_E_INVALIDPATTERNSTRING  0xFEB6
#define AFX_IDP_E_INVALIDUSEOFNULL      0xFEB7
#define AFX_IDP_E_INVALIDFILEFORMAT     0xFEB8
#define AFX_IDP_E_INVALIDPROPERTYVALUE  0xFEB9
#define AFX_IDP_E_INVALIDPROPERTYARRAYINDEX 0xFEBA
#define AFX_IDP_E_SETNOTSUPPORTEDATRUNTIME 0xFEBB
#define AFX_IDP_E_SETNOTSUPPORTED       0xFEBC
#define AFX_IDP_E_NEEDPROPERTYARRAYINDEX 0xFEBD
#define AFX_IDP_E_SETNOTPERMITTED       0xFEBE
#define AFX_IDP_E_GETNOTSUPPORTEDATRUNTIME 0xFEBF
#define AFX_IDP_E_GETNOTSUPPORTED       0xFEC0
#define AFX_IDP_E_PROPERTYNOTFOUND      0xFEC1
#define AFX_IDP_E_INVALIDCLIPBOARDFORMAT 0xFEC2
#define AFX_IDP_E_INVALIDPICTURE        0xFEC3
#define AFX_IDP_E_PRINTERERROR          0xFEC4
#define AFX_IDP_E_CANTSAVEFILETOTEMP    0xFEC5
#define AFX_IDP_E_SEARCHTEXTNOTFOUND    0xFEC6
#define AFX_IDP_E_REPLACEMENTSTOOLONG   0xFEC7
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
